name: lops
channels:
  - defaults
dependencies:
  - python=3.6.4
  - numpy
  - scipy
  - matplotlib
  - ipython
  - pytest
  - Sphinx
  - numpydoc
  - pip:
    - pytest-runner
    - sphinx-rtd-theme
    - sphinx-gallery
    - nbsphinx
    - image